spring:
  datasource:
    url: jdbc:mysql://localhost:3306/books?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ss
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver